apiVersion: v1
kind: Service
metadata:
 name: internet-banking
 namespace: model-app
 annotations:
   service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
spec:
 selector:
   run: model-app
 ports:
   - protocol: TCP
     port: 3000
     targetPort: 3000
     name: http
 type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: internet-banking
 namespace: model-app
spec:
 selector:
   matchLabels:
     run: model-app
 template:
   metadata:
     labels:
       run: model-app
       app.kubernetes.io/version: "1.0"
   spec:
     containers:
     - name: frontend
       image: nikhilgoenka/samplebank-nginx:blue
       imagePullPolicy: Always
       ports:
       - containerPort: 3000
         protocol: TCP
